import type {
  ArtifactManifest,
  ChartSpec,
  DatasetProvenance,
  DemoDataset,
  ModelRun,
  NwbTreeNode,
} from "@/lib/contracts";

const verified = <T,>(value: T, note: string) =>
  ({ status: "verified", value, note }) as const;

export const primaryDatasetProvenance: DatasetProvenance = {
  id: "primary-public-nwb",
  title: verified("Conjunctive Representation of Position, Direction, and Velocity in Entorhinal Cortex", "Immutable published Dandiset record."),
  authors: verified(["Francesca Sargolini", "Marianne Fyhn", "Torkel Hafting", "Bruce L. McNaughton", "Menno P. Witter", "May-Britt Moser", "Edvard I. Moser", "Haagen Waade", "Simon Ball"], "Official DANDI author order."),
  repository: verified("DANDI Archive · Dandiset 000582", "Official public NWB archive."),
  permanentIdentifier: verified("https://doi.org/10.48324/dandi.000582/0.251111.2151", "Published version DOI."),
  license: verified("CC-BY-4.0", "Applies to the selected Dandiset version and attributed derivative."),
  species: verified("Rattus norvegicus (Long Evans rat)", "Read from the DANDI record and NWB metadata."),
  brainRegion: verified("Medial entorhinal cortex, layer II (MEC LII)", "Recorded source region."),
  recordingModality: verified("Extracellular electrophysiology with sorted spike times, LFP, and two-dimensional LED position", "Recorded source modality; the compact derivative selects spike times and LED1 position."),
  selectedUnitsOrChannels: verified("Eight sorted units: t1c1, t2c1, t2c3, t3c1, t3c2, t3c3, t3c4, t4c1", "Exact IDs from the selected NWB Units table."),
  behavioralVariables: verified(["LED1 x position in meters", "LED1 y position in meters", "project-derived descriptive speed in meters/second"], "Only LED1 x/y are source fields; descriptive speed uses sample-centered finite differences on the 10 Hz derivative, one-sided at endpoints, without smoothing. The predictive lane separately uses trailing-only speed."),
  selectedFilesOrSessions: verified(["sub-10073/sub-10073_ses-17010302_behavior+ecephys.nwb", "asset UUID 2b9e441b-56bc-4be2-893e-0e02d22d239d", "SHA-256 43b3b435b953d22e276acc494af2926b63deaf15d2834531b2a87d08a8458a09", "session label 17010302 (not interpreted as a date)"], "Exact immutable asset path, UUID, checksum, and archive session label."),
  transformations: verified(["Verify 15,657,857 source bytes against the pinned SHA-256", "Apply SpatialSeries conversion 0.01 and offset 0.0 exactly once", "Select every fifth 20 ms position sample without interpolation to create a 100 ms derivative over 600 seconds", "Retain all spike times for eight reviewed unit IDs", "Bin spikes into fixed 100 ms intervals", "Derive descriptive speed with sample-centered finite differences and one-sided endpoints, without smoothing", "Build documented descriptive arrays and compact web artifacts"], "Generation scripts, provenance, validation report, and manifest record parameters and hashes."),
  accessDate: verified("2026-07-14", "Official archive and tool sources reviewed on this date."),
  containsPrivateOrClinicalData: false,
};

export const syntheticFallbackDataset: DemoDataset = {
  id: "synthetic-neural-fallback",
  label: "Synthetic neural time-series fallback",
  origin: "synthetic",
  provenanceId: "synthetic-generator-v1",
  timeUnit: "seconds",
  responseUnit: "spike count",
  variables: [
    { key: "time", label: "Elapsed time", unit: "s", role: "time" },
    { key: "behavior", label: "Synthetic behavioral covariate", unit: "a.u.", role: "behavior" },
    { key: "spike_count", label: "Synthetic binned spike count", unit: "count/bin", role: "neural" },
    { key: "split", label: "Evaluation partition", unit: "category", role: "condition" },
  ],
  disclosure:
    "A deterministic numeric fallback is bundled and remains labeled synthetic in every chart, route, URL state, and export.",
};

export const artifactManifest = [
  {
    id: "public-nwb-derivative",
    label: "Compact public-NWB derivative",
    kind: "dataset",
    status: "available",
    origin: "public-derived",
    execution: "precomputed",
    generatedBy: "scripts/build_artifacts.py → python/neurostack_explorer/artifacts.py",
    version: "1.0.0",
    path: "/artifacts/v1/demo-dataset.json",
    disclosure: "Derived from DANDI 000582@0.251111.2151 under CC BY 4.0; artifact SHA-256 e56d1ded0dad948c2d3ddb82fc23b3ed2f1280dfc6f341c538ecf06a0c307e64.",
  },
  {
    id: "synthetic-fallback",
    label: "Synthetic fallback dataset",
    kind: "dataset",
    status: "available",
    origin: "synthetic",
    execution: "precomputed",
    generatedBy: "scripts/build_artifacts.py → python/neurostack_explorer/artifacts.py",
    version: "1.0.0",
    seed: 20260714,
    path: "/artifacts/v1/synthetic-dataset.json",
    disclosure: "Deterministic nonbiological fallback; artifact SHA-256 ad63cff4be0401f28a53f215a414edf5df5f311ac66f4260306a915d46deda49.",
  },
  {
    id: "analysis-notebook",
    label: "Executed NeuroStack Explorer notebook",
    kind: "notebook",
    status: "available",
    origin: "public-derived",
    execution: "precomputed",
    generatedBy: "scripts/create_notebook.py + scripts/execute_notebook.py",
    version: "1.0.0",
    path: "/artifacts/v1/neurostack-explorer.ipynb",
    disclosure: "Executed 15-section notebook. It checksum-gates and loads the cached NWB source, builds Pynapple objects, refits the deterministic NeMoS, scikit-learn, and PyTorch lanes, inspects the checksummed Stan artifact, and renders a Plotly output. Its exact SHA-256 is recorded in notebook-manifest.json.",
  },
  {
    id: "model-artifacts",
    label: "Aligned model-comparison outputs",
    kind: "model",
    status: "available",
    origin: "public-derived",
    execution: "precomputed",
    generatedBy: "scripts/run_models.py",
    version: "artifact 1.0.0 · task next-bin-count-v2",
    seed: 20260714,
    path: "/artifacts/v1/model-results.json",
    disclosure: "Executed NeMoS, scikit-learn, PyTorch, and Stan outputs for one selected unit and one frozen chronological split; SHA-256 f52bb8738cd375a47aaa56dd4601f1f39d78f35fb10425ca4821d05869b57371. Scores are demonstrations, not benchmarks or causal evidence.",
  },
  {
    id: "plenoptic-artifacts",
    label: "Visual-model synthesis checkpoints",
    kind: "image",
    status: "available",
    origin: "illustrative",
    execution: "precomputed",
    generatedBy: "scripts/generate_plenoptic_demo.py",
    version: "artifact 1.0.0 · plenoptic 2.0.1",
    seed: 20260714,
    path: "/artifacts/v1/plenoptic-demo.json",
    disclosure: "Executed 24×24 procedural-image Metamer synthesis with a fixed Gaussian model; SHA-256 dec853e652b90a2945721fed15efe4bff8ff0b999a09d11c9c5b23415c786636. It is separate from the DANDI recording and does not establish human perceptual equivalence.",
  },
  {
    id: "bridgestan-surface",
    label: "Two-parameter log-density surface",
    kind: "model",
    status: "available",
    origin: "illustrative",
    execution: "precomputed",
    generatedBy: "scripts/generate_bridgestan_demo.py",
    version: "artifact 1.0.0 · BridgeStan 2.9.0",
    seed: 20260714,
    path: "/artifacts/v1/bridgestan-surface.json",
    disclosure: "Compiled 17×17 illustrative log-density surface with a finite-difference gradient check and deterministic nine-step trace; SHA-256 1b7a465368d9b5c39e49fae1b0d30f00b1e250a7ea5038251a0edff2ff9fd971. It is not a result from the primary dataset.",
  },
] as const satisfies readonly ArtifactManifest[];

export const alignedModelRuns = [
  {
    id: "nemos-glm",
    label: "NeMoS next-bin rate GLM",
    family: "glm",
    researchQuestion: "How well can documented current-or-past covariates predict a selected unit’s firing rate in the next 100 ms bin?",
    target: "Selected unit next-bin firing rate (spikes/s), fit as the equivalent 100 ms spike count where required",
    inputs: ["Current-bin x position (m)", "Current-bin y position (m)", "Trailing-only speed from current and prior positions (m/s)", "Current-bin t1c1 spike count"],
    assumptions: ["Poisson likelihood with exponential inverse link", "Ridge strength 0.01", "Training-only standardization", "Six-configuration basis explorer is computed separately and not used in this fitted lane"],
    splitStrategy: "5,999 rows: train [0,3600), validation [3600,4200), 30 s gap [4200,4500), final test [4500,5999); zero-based half-open indices",
    evaluation: ["Validation mean Poisson deviance 0.759256", "Final-test mean Poisson deviance 0.848559 on all 1,499 rows", "Displayed trace decimated only for display at stride 5"],
    seed: 20260714,
    origin: "public-derived",
    execution: "precomputed",
    artifactStatus: "available",
    disclosure: "Actually fit with NeMoS 0.2.9/JAX 0.10.1 using Poisson Ridge (0.01) and LBFGS. NeMoS also computes a separate basis artifact that is explicitly excluded from this raw-feature fit. This one-session prediction demonstration is not causal evidence or a population benchmark.",
  },
  {
    id: "sklearn-poisson-baseline",
    label: "scikit-learn Poisson baseline",
    family: "baseline",
    researchQuestion: "What next-bin rate prediction is available from a simple, leakage-aware count baseline?",
    target: "Selected unit next-bin firing rate (spikes/s), represented as a 100 ms count for fitting",
    inputs: ["Current-bin x position (m)", "Current-bin y position (m)", "Trailing-only speed from current and prior positions (m/s)", "Current-bin t1c1 spike count"],
    assumptions: ["PoissonRegressor alpha 0.1 selected from [0, 0.001, 0.01, 0.1]", "Fold-local standardization", "Three expanding-window folds contained inside outer training"],
    splitStrategy: "Three alpha-selection folds stay inside train [0,3600); outer validation [3600,4200), 30 s gap [4200,4500), and final test [4500,5999) do not participate in alpha selection",
    evaluation: ["Outer-validation mean Poisson deviance 0.764638", "Final-test mean Poisson deviance 0.853491 on all 1,499 rows", "Training-mean reference: validation 0.900410; final test 1.111981", "Coefficient and fold inspection"],
    seed: 20260714,
    origin: "public-derived",
    execution: "precomputed",
    artifactStatus: "available",
    disclosure: "Actually fit with scikit-learn 1.9.0. Training-only expanding-window cross-validation selected alpha 0.1; outer validation and final test were not used for selection.",
  },
  {
    id: "pytorch-poisson-mlp",
    label: "Small PyTorch Poisson-output MLP",
    family: "neural-network",
    researchQuestion: "Does limited nonlinear capacity improve held-out next-bin rate prediction without unstable overfitting?",
    target: "Selected unit next-bin firing rate (spikes/s), represented as a 100 ms count for fitting",
    inputs: ["Current-bin x position (m)", "Current-bin y position (m)", "Trailing-only speed from current and prior positions (m/s)", "Current-bin t1c1 spike count"],
    assumptions: ["Three predeclared candidates: 4–1, 4–8–1, and regularized 4–8–1", "CPU float64 deterministic algorithms", "Training-only standardization"],
    splitStrategy: "Same frozen blocks as the GLMs; validation selects the candidate and its early-stopping checkpoint, with final test untouched",
    evaluation: ["Regularized 4–8–1 selected at epoch 22 with weight decay 0.001", "Validation mean Poisson deviance 0.694164", "Final-test mean Poisson deviance 0.778533 on all 1,499 rows", "All three candidate validation and final-test results remain recorded"],
    seed: 20260714,
    origin: "public-derived",
    execution: "precomputed",
    artifactStatus: "available",
    disclosure: "Actually trained with PyTorch 2.12.1 on CPU using deterministic operations and Adam. Its lower score on this one split is not a general superiority claim.",
  },
  {
    id: "stan-uncertainty",
    label: "Stan neural-response uncertainty model",
    family: "bayesian",
    researchQuestion: "What coefficient uncertainty does a Poisson-log model report for the same next-bin t1c1 task under explicit priors?",
    target: "t1c1 spike count in the next 100 ms bin",
    inputs: ["The same four standardized predictors as the aligned models", "alpha ~ normal(-1, 1.5)", "beta ~ normal(0, 1)"],
    assumptions: ["Poisson-log likelihood", "Training subsample stride 5", "Two-chain posterior sampling"],
    splitStrategy: "Same frozen validation/gap/test blocks; posterior fit uses every fifth training row and does not tune on validation or test",
    evaluation: ["Validation mean Poisson deviance 0.772936", "Final-test mean Poisson deviance 0.850890 on all 1,499 rows", "0 divergences; max R-hat 1.01129; minimum bulk ESS 887.091", "Held-out total observed 398 versus posterior-predictive 90% interval [428, 581.1]", "1,443 of 1,499 held-out rows inside their empirical 90% predictive intervals"],
    seed: 20260714,
    origin: "public-derived",
    execution: "precomputed",
    artifactStatus: "available",
    disclosure: "Actually sampled with CmdStanPy 1.3.0/CmdStan 2.39.0 using two chains, 500 warmup and 500 sampling draws per chain. A separate seeded Poisson simulation produces the held-out posterior-predictive check. Both depend on the declared likelihood, priors, and training subsample.",
  },
  {
    id: "bridgestan-interface",
    label: "BridgeStan two-parameter interface demo",
    family: "interface-demo",
    researchQuestion: "What log-density and gradient information can external code request from a compiled model?",
    target: "Illustrative two-parameter surface",
    inputs: ["Two unconstrained illustrative parameters"],
    assumptions: ["Independent standard-normal terms plus 0.35 × parameter product", "17×17 fixed grid", "Jacobian true and propto false"],
    splitStrategy: "Not a predictive model and not part of the dataset comparison",
    evaluation: ["Finite-difference gradient check passed with maximum absolute error 2×10⁻¹⁰", "Nine deterministic gradient-ascent evaluations", "Regeneration equality"],
    seed: 20260714,
    origin: "illustrative",
    execution: "precomputed",
    artifactStatus: "available",
    disclosure: "Actually evaluated with BridgeStan 2.9.0 against the compiled two-parameter Stan program. Teaching interface only; not a biological result.",
  },
] as const satisfies readonly ModelRun[];

export const plannedCharts = [
  {
    id: "linked-raster",
    title: "Selected-unit spike raster",
    purpose: "Inspect event timing within the selected supported interval.",
    chartType: "raster",
    xLabel: "Time (s)",
    yLabel: "Unit identifier",
    origin: "public-derived",
    execution: "client-derived",
    accessibleSummary: "Reports the selected interval, displayed units, event count, and visible concentration without causal interpretation.",
  },
  {
    id: "population-rate",
    title: "Population firing-rate heatmap",
    purpose: "Compare relative rate structure across units and time bins.",
    chartType: "heatmap",
    xLabel: "Time (s)",
    yLabel: "Unit identifier",
    origin: "public-derived",
    execution: "client-derived",
    accessibleSummary: "Identifies the selected range, 100 ms bin size, normalization, and broad high- or low-rate structure.",
  },
  {
    id: "tuning-interval",
    title: "Occupancy-aware tuning curve",
    purpose: "Relate a behavioral variable to firing rate while displaying occupancy.",
    chartType: "interval",
    xLabel: "Project-derived speed (m/s)",
    yLabel: "Firing rate (spikes/s)",
    origin: "public-derived",
    execution: "client-derived",
    accessibleSummary: "Describes occupied speed bins, firing-rate pattern, and under-sampled regions for the selected unit.",
  },
  {
    id: "posterior-summary",
    title: "Posterior parameter summary",
    purpose: "Expose posterior shape and credible intervals with prior context.",
    chartType: "interval",
    xLabel: "Standardized coefficient value",
    yLabel: "Parameter",
    origin: "public-derived",
    execution: "precomputed",
    accessibleSummary: "States the posterior median, central 90% interval, prior, R-hat, bulk ESS, and the limits of this one-session Poisson-log model.",
  },
  {
    id: "bridgestan-surface-chart",
    title: "Illustrative log-density surface",
    purpose: "Connect a parameter vector to local density and gradient information.",
    chartType: "surface",
    xLabel: "Illustrative parameter 1",
    yLabel: "Illustrative parameter 2",
    origin: "illustrative",
    execution: "precomputed",
    accessibleSummary: "Reports the current point, log density, gradient components, and deterministic proposed step from the illustrative compiled model.",
  },
] as const satisfies readonly ChartSpec[];

export const nwbHierarchySpec: readonly NwbTreeNode[] = [
  {
    id: "general",
    label: "General metadata",
    kind: "group",
    description: "Session, institution, experimenter, file, and schema metadata that pass the public-data privacy review.",
  },
  {
    id: "acquisition",
    label: "Acquisition",
    kind: "group",
    description: "Raw or acquired time series included in the selected public file.",
  },
  {
    id: "processing",
    label: "Processing",
    kind: "group",
    description: "Derived processing modules retained by the source file.",
  },
  {
    id: "units",
    label: "Units",
    kind: "table",
    description: "Public unit metadata and event-time references used by the analysis derivative.",
  },
  {
    id: "intervals",
    label: "Trials and intervals",
    kind: "group",
    description: "Named time intervals, trials, or behavioral states, when present and documented.",
  },
  {
    id: "electrodes",
    label: "Electrodes",
    kind: "table",
    description: "Public recording-device and location metadata used to interpret channels or units.",
  },
  {
    id: "stimulus",
    label: "Stimulus",
    kind: "group",
    description: "Stimulus time series or presentations, only if present in the selected dataset.",
  },
  {
    id: "behavior",
    label: "Behavior",
    kind: "group",
    description: "Documented behavioral measurements aligned to supported time intervals.",
  },
];

export const methodsSections = [
  {
    title: "1. Source and license gate",
    summary: "Use only the pinned DANDI 000582@0.251111.2151 asset after its authorship, CC BY 4.0 terms, public status, checksum, and selected session metadata pass review.",
    checks: ["Official DANDI record", "Immutable version DOI", "CC BY 4.0", "No private or clinical data", "Exact asset, SHA-256, and access date"],
  },
  {
    title: "2. Immutable source, documented derivative",
    summary: "Keep source identity separate from the compact derivative and make every field selection, time restriction, binning step, and normalization reproducible.",
    checks: ["Source identity hash", "Derivative script version", "Selected paths", "Units and support intervals", "Output hash"],
  },
  {
    title: "3. Temporal validation",
    summary: "Validate the 20 ms source position stream, 100 ms derivative grid, monotonic timestamps, 600-second support, interval boundaries, and recorded source caveats before analysis.",
    checks: ["Monotonic time", "20 ms source and 100 ms derivative intervals", "600-second support", "Bin edge policy", "Finite selected values and explicit exclusions"],
  },
  {
    title: "4. Leakage-safe feature engineering",
    summary: "Use the frozen next-bin-count-v2 split and fit standardization only on training rows; predictive speed is trailing-only so it cannot see a future position.",
    checks: ["Train [0,3600)", "Validation [3600,4200)", "Gap [4200,4500)", "Test [4500,5999)", "Training-only scaling and trailing-only speed"],
  },
  {
    title: "5. Aligned prediction question",
    summary: "Compare NeMoS, scikit-learn, PyTorch, and the Stan posterior-mean prediction on the same t1c1 next-bin count task, inputs, frozen split, and final-test deviance.",
    checks: ["Same target", "Same four inputs", "Same blocked split", "All 1,499 test rows", "Display-only stride disclosed"],
  },
  {
    title: "6. Uncertainty and diagnostic lane",
    summary: "Use the computed Stan lane to expose coefficient uncertainty under its Poisson-log likelihood and explicit priors, while keeping its subsampled training design visible.",
    checks: ["Committed model source", "Explicit priors", "Fixed seed", "0 divergences", "R-hat and bulk ESS"],
  },
  {
    title: "7. Precompute with disclosure",
    summary: "Generate expensive models and synthesis offline, then label replayed artifacts as precomputed while limiting client work to deterministic exploration.",
    checks: ["Origin label", "Execution label", "Generator path", "Version and seed", "Cache identity"],
  },
  {
    title: "8. Accessible scientific communication",
    summary: "Pair every chart with units, controls that work without hover, a textual summary, noncolor encoding, and a reduced-motion or static state.",
    checks: ["Axis units", "Keyboard path", "Visible focus", "Text summary", "Static fallback"],
  },
] as const;
