import type { SourceReference } from "@/lib/contracts";

const accessed = "2026-07-14";

/**
 * First-party technical sources and the exact releases used or compatibility-
 * tested by the project. The production environment lock remains the final
 * authority for transitive versions.
 */
export const sourceRegistry: readonly SourceReference[] = [
  {
    id: "python",
    toolName: "Python",
    verification: "verified",
    website: "https://www.python.org/",
    documentation: "https://docs.python.org/3.12/",
    repository: "https://github.com/python/cpython",
    license: "Python Software Foundation License 2.0",
    version: "3.12.x analysis lane",
    accessDate: accessed,
    citation: "Python Software Foundation. Python 3.12 documentation.",
    note: "Python orchestrates the offline analysis; the public site never executes visitor-supplied Python.",
  },
  {
    id: "jupyterlab",
    toolName: "JupyterLab",
    verification: "verified",
    website: "https://jupyter.org/",
    documentation: "https://jupyterlab.readthedocs.io/",
    repository: "https://github.com/jupyterlab/jupyterlab",
    license: "BSD-3-Clause",
    version: "Notebook format + nbclient 0.10.2 · ipykernel 6.30.1; JupyterLab UI not installed in the release lock",
    accessDate: accessed,
    citation: "Project Jupyter. JupyterLab documentation.",
    note: "The committed .ipynb is compatible with JupyterLab and was executed headlessly with nbclient/ipykernel. The release lock does not claim a tested JupyterLab desktop/server version, and the site exposes no unrestricted kernel.",
  },
  {
    id: "pynapple",
    toolName: "Pynapple",
    verification: "verified",
    website: "https://pynapple.org/",
    documentation: "https://pynapple.org/examples/tutorial_pynapple_dandi.html",
    repository: "https://github.com/pynapple-org/pynapple/tree/v0.11.3",
    license: "MIT",
    version: "0.11.3",
    accessDate: accessed,
    citation: "Pynapple 0.11.3 documentation and DANDI tutorial.",
    note: "The executed lane constructs current Pynapple time-series objects and independently verifies the 100 ms t1c1 count vector. Browser tuning and correlogram controls are bounded TypeScript views over the checksummed artifact, not Python execution.",
  },
  {
    id: "nemos",
    toolName: "NeMoS",
    verification: "verified",
    website: "https://nemos.readthedocs.io/",
    documentation: "https://nemos.readthedocs.io/en/stable/quickstart.html",
    repository: "https://github.com/flatironinstitute/nemos/tree/0.2.9",
    license: "MIT",
    version: "0.2.9",
    accessDate: accessed,
    citation: "Flatiron Institute. NeMoS 0.2.9.",
    note: "JAX compilation and model fitting ran offline on the frozen four-feature task; the browser inspects checksummed coefficients and held-out predictions without refitting.",
  },
  {
    id: "plenoptic",
    toolName: "plenoptic",
    verification: "verified",
    website: "https://docs.plenoptic.org/",
    documentation: "https://docs.plenoptic.org/",
    repository: "https://github.com/plenoptic-org/plenoptic/tree/2.0.1",
    license: "MIT",
    version: "2.0.1",
    accessDate: accessed,
    citation: "plenoptic 2.0.1 documentation.",
    note: "Version 2 namespaces are used. A fixed eval-mode PyTorch visual model and seeded precomputed synthesis are required.",
  },
  {
    id: "stan",
    toolName: "Stan + CmdStanPy",
    verification: "verified",
    website: "https://mc-stan.org/",
    documentation: "https://mc-stan.org/cmdstanpy/installation.html",
    repository: "https://github.com/stan-dev/stan",
    license: "BSD-3-Clause",
    version: "CmdStanPy 1.3.0 · CmdStan 2.39.0",
    accessDate: accessed,
    citation: "Stan Development Team. Stan and CmdStanPy documentation.",
    note: "The project does not install the unrelated PyPI package named stan. Inference is reproducibly precomputed.",
  },
  {
    id: "bridgestan",
    toolName: "BridgeStan",
    verification: "verified",
    website: "https://roualdes.us/bridgestan/latest/",
    documentation: "https://roualdes.us/bridgestan/latest/languages/python.html",
    repository: "https://github.com/roualdes/bridgestan",
    license: "BSD-3-Clause",
    version: "2.9.0",
    accessDate: accessed,
    citation: "BridgeStan 2.9.0 documentation.",
    note: "The two-parameter interface demo records unconstrained coordinates, propto and Jacobian settings; it is not a biological model result.",
  },
  {
    id: "figurl",
    toolName: "Figurl",
    verification: "verified",
    website: "https://github.com/flatironinstitute/figurl",
    documentation: "https://github.com/flatironinstitute/figurl",
    repository: "https://github.com/flatironinstitute/figurl",
    license: "Apache-2.0",
    version: "0.3.1 package status reviewed",
    accessDate: accessed,
    citation: "Flatiron Institute. Figurl source repository.",
    note: "Direct hosting depends on Kachery cloud and durable file ownership. This project therefore ships an accurately labeled Figurl-inspired Scientific Figure Viewer, not an official Figurl instance.",
  },
  {
    id: "pytorch",
    toolName: "PyTorch",
    verification: "verified",
    website: "https://pytorch.org/",
    documentation: "https://docs.pytorch.org/docs/stable/notes/randomness.html",
    repository: "https://github.com/pytorch/pytorch",
    license: "BSD-style",
    version: "2.12.1 conservative lock lane",
    accessDate: accessed,
    citation: "PyTorch documentation, including reproducibility notes.",
    note: "CPU artifacts record exact version, device and seed because reproducibility is not guaranteed across releases and platforms.",
  },
  {
    id: "scikit-learn",
    toolName: "scikit-learn",
    verification: "verified",
    website: "https://scikit-learn.org/",
    documentation: "https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.TimeSeriesSplit.html",
    repository: "https://github.com/scikit-learn/scikit-learn",
    license: "BSD-3-Clause",
    version: "1.9.0",
    accessDate: accessed,
    citation: "scikit-learn 1.9.0 documentation.",
    note: "The project uses one frozen chronological train/validation/gap/test split and training-only standardization instead of random shuffling.",
  },
  {
    id: "plotly",
    toolName: "Plotly",
    verification: "verified",
    website: "https://plotly.com/python/",
    documentation: "https://plotly.com/javascript/react/",
    repository: "https://github.com/plotly/plotly.js",
    license: "MIT",
    version: "plotly.js 3.7.0 · plotly.py 6.8.0",
    accessDate: accessed,
    citation: "Plotly Python and JavaScript documentation.",
    note: "One Plotly instance is lazy-loaded at a time; repeated self-contained multi-megabyte HTML exports are avoided.",
  },
  {
    id: "nwb",
    toolName: "NWB + PyNWB + DANDI",
    verification: "verified",
    website: "https://nwb.org/",
    documentation: "https://docs.dandiarchive.org/user-guide-sharing/validating-files/",
    repository: "https://github.com/NeurodataWithoutBorders/pynwb",
    license: "BSD-3-Clause (PyNWB) · dataset CC-BY-4.0",
    version: "NWB schema 2.10.0 · PyNWB 3.1.3 lock lane · DANDI CLI 0.76.7",
    accessDate: accessed,
    citation: "Neurodata Without Borders, PyNWB, and DANDI Archive documentation.",
    note: "The immutable source asset reports NWB 2.6.0 and is verified by Dandiset version, asset UUID, exact path, byte size, and SHA-256. The current PyNWB/NWB schema lane is recorded separately. Visitor uploads are not accepted.",
  },
] as const;
